config/routes.rb
Rails.application.routes.draw do
 ActiveAdmin.routes(self)
  devise_for :users
  get 'comments/create'
	
	root 'photos#index'
	resources :users
  resources :photos do 
  	resources :comments
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/adapters/only_admins.rb
class Adapters::OnlyAdmins < ActiveAdmin::AuthorizationAdapter

  def authorized?(action, subject = nil)
    user.admin?
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :photo

  def self.average_score
    average(:score)
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
	has_many :comments
  belongs_to :user
  mount_uploader :avatar, AvatarUploader
end

app/models/user.rb
class User < ApplicationRecord
	has_many :photos, dependent: :destroy
	has_many :comments, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable
	validates :name, presence: true, length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def access_denied(exception)
    flash[:danger] = exception.message
    redirect_to root_url
  end

  
  private
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:admin, :name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:admin, :name])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    @photo = Photo.find(params[:photo_id])
    @comment = @photo.comments.create(comment_params)
    @comment.user_id = current_user.id
    
    if @comment.save
      redirect_to @photo
    else
      flash.now[:danger] = "error while saving comment"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :score)
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	before_action :photo_owner, only: [:edit, :update, :destroy]
	before_action :authenticate_user!
	def index
		@photos = Photo.all.order('created_at DESC')
  end
  def new
  	@photo =  current_user.photos.new
  end

  def create
  	@photo =  current_user.photos.new(photo_params)
  	if @photo.save
        redirect_to root_path, :flash => { :notice => "Photo successfully added" }
      else
      render 'new'
      end
  end

  def show
  	@photo = Photo.find(params[:id])
    @select_list = { '5':5, '4':4, '3':3, '2':2, '1':1 }
  end

  def destroy
    @photo.destroy
      redirect_to root_path, :flash => { :notice => "Photo successfully deleted" }
  end

  private
    def photo_params
      params.require(:photo).permit(:name, :user_id, :avatar)
    end

    def photo_owner
      @photo = Photo.find(params[:id])
      if(  @photo.user_id != current_user.id)
        flash[:notice] = 'Access denied as you are not owner of this Notice'
        redirect_to root_path
      end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 def show
    @user = User.find(params[:id])
    @photos = @user.photos
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<li>
  <p>
    By: <strong><%= comment.user.name %>, score: <%= comment.score %></strong>
  </p>
  <p>
    <%= comment.body %>
  </p>
</li>

app/views/comments/_form.html.erb
<%= form_for [@photo, @photo.comments.build] do |f| %>
    <div>
      Text: <%= f.text_area :body %>
    </div>
    <div>
      Score: <%= f.select :score, @select_list %>
    </div>

    <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Contr6</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/application/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/application/_navbar.html.erb
<nav class="navbar navbar-fixed-top navbar-light bg-light">
  <div class="container">
    <div class="navbar-header">
      
      <%= link_to 'Main Page', root_path, class: 'navbar-link' %>
    </div>

    
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <p class="navbar-text">
            Hello, <%= link_to current_user.name, edit_user_registration_path(current_user), class: 'navbar-link' %>
          </p>
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Edit profile', edit_user_registration_path(current_user) %></li>
                <li><%= link_to 'Create Photo', new_photo_path(current_user) %></li>
                <% if current_user.admin? %>
                <li><%= link_to 'Photo Profile', user_path(current_user) %></li>
                <li><%= link_to 'Admin', admin_root_path %></li>
                <% end %>
                <li class="divider"></li>
                <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          </ul>
        <% else %>
          <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-default navbar-btn' %>
          <%= link_to 'Log in', new_user_session_path, class: 'btn btn-default navbar-btn' %>
        <% end %>
      </ul>
    
  </div>
</nav>

app/views/photos/edit.html.erb
<h1>Photos#edit</h1>
<p>Find me in app/views/photos/edit.html.erb</p>

app/views/photos/index.html.erb
<% @photos.each do |photo| %>
<div class="gallery">
  <a target="_blank">
    <%= image_tag photo.avatar.thumb.url %>
    <div class="desc">
      <% if current_user.try(:admin?) or user_signed_in? %>
        <%= link_to photo.name, photo_path(photo) %></p>
        By: <%= link_to photo.user.name, user_path(photo.user) %>
      <% else %>
        <p><%= photo.name %></p>
        <p>By:<%= photo.user.name %></p>
      <% end %>
      </div>
  </a>
</div>
<% end %>

app/views/photos/new.html.erb
<%= simple_form_for @photo do |f| %>
  <%= f.input :name, required: true %>
  <%= f.input :avatar, as: :file, label: 'Photo',required: true %>
  <%= f.button :submit %>
<% end %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @photo.name %></h1>
<%= image_tag @photo.avatar_url %>
<br> Average score: <%= @photo.comments.average_score %>

<h2><%= link_to 'Comments', '#', id: 'comments-link' %></h2>
<div id="comment-section">
  <ol id="comments">
    <%= render @photo.comments %>
  </ol>
<% if user_signed_in? %>
<h3>Add a comment:</h3>
  <%= render 'comments/form' %>
</div>
<% end %>

app/views/users/show.html.erb
<h1> <%= @user.name %>'s Profile </h1>
<% if current_user == @user %>
  <%= link_to 'Create new photo', new_photo_path %>
<% end %>

<table class="table table-stripped">
  <thead>
    <tr>
      <th>Photo</th>
      <th>Name</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= image_tag photo.avatar.thumb.url %></td>
        <td><%= link_to photo.name, photo %></td>
        <% if current_user == @user %>
          <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>